name: npm-install
description: Install Node, npm and dependencies
runs:
  using: 'composite'
  steps:
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: npm
    - name: Install dependencies
      run: npm install
      shell: bash
