name: dependencies
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 6 * * 3

env:
  FORCE_COLOR: 1

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/npm-install
      - name: Update Dependencies
        run: npm run dependency-update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          committer: GitHub Actions <actions@github.com>
          commit-message: 'Update dependencies'
          title: 'Update dependencies'
          body: 'Please look at the diff for changes'
          author: GitHub Actions <actions@github.com>
          branch: chore/update-dependencies
          branch-suffix: timestamp
