name: release-docker-latest

on:
  push:
    tags:
      - '*'

concurrency: release-docker-latest

env:
  FORCE_COLOR: 1

jobs:
  release:
    runs-on: buildjet-8vcpu-ubuntu-2204
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-publish
        with:
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
