name: release-docker-develop

on:
  push:
    branches:
      - main

concurrency: release-docker-develop

env:
  FORCE_COLOR: 1

jobs:
  release:
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/docker-publish
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          tags: develop
