name: release-docker-develop

on:
  push:
    branches:
      - main

concurrency: release-docker-develop

env:
  FORCE_COLOR: 1

jobs:
  release:
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Get git commit
        id: git-commit
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/docker-publish
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/kennethwussmann/zeitraum/server:develop,ghcr.io/kennethwussmann/zeitraum/server:${{ steps.agit-commit.outputs.SHORT_SHA }}
          build-args: VERSION=${{ steps.agit-commit.outputs.SHORT_SHA }}
